<script setup lang="ts">
import {computed, reactive, ref, watch} from 'vue'
import type {Note, NotePayload} from '../types/note'
import {formatDateTime, isEdited} from '../utils/date'
import BaseInput from './BaseInput.vue'
import BaseButton from './BaseButton.vue'

// Matches the API's [MaxLength(200)] on Title
const TITLE_MAX_LENGTH = 200

const props = defineProps<{
  open: boolean
  note: Note | null
  isSaving: boolean
  errorMessage: string | null
}>()

const emit = defineEmits<{
  close: []
  submit: [payload: NotePayload]
}>()

const form = reactive({title: '', content: ''})
const titleError = ref<string | null>(null)

const isEditMode = computed(() => props.note !== null)

watch(
    () => [props.open, props.note] as const,
    ([isOpen, note]) => {
      if (!isOpen) return
      form.title = note?.title ?? ''
      form.content = note?.content ?? ''
      titleError.value = null
    },
    {immediate: true},
)

watch(
    () => form.title,
    () => {
      if (titleError.value && form.title.trim()) titleError.value = null
    },
)

function handleSubmit(): void {
  const title = form.title.trim()
  if (!title) {
    titleError.value = 'Title is required.'
    return
  }
  emit('submit', {title, content: form.content.trim() || null})
}
</script>

<template>
  <div
      v-if="open"
      class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4"
      @click.self="emit('close')"
  >
    <div class="w-full max-w-lg rounded-2xl bg-surface p-6 shadow-xl" role="dialog" aria-modal="true"
         aria-labelledby="note-form-title">
      <h2 id="note-form-title" class="text-lg font-semibold text-heading">{{
          isEditMode ? 'Edit note' : 'New note'
        }}</h2>

      <form class="mt-4 space-y-4" novalidate @submit.prevent="handleSubmit">
        <BaseInput
            v-model="form.title"
            label="Title"
            placeholder="Give your note a title"
            required
            :maxlength="TITLE_MAX_LENGTH"
            :error="titleError"
        >
          <template #hint>
            <p class="mt-1 text-right text-xs text-muted">{{ form.title.length }}/{{ TITLE_MAX_LENGTH }}</p>
          </template>
        </BaseInput>

        <label class="block">
          <span class="mb-1 block text-sm font-medium text-heading">Content <span class="font-normal text-muted">(optional)</span></span>
          <textarea
              v-model="form.content"
              rows="6"
              placeholder="Write your note…"
              class="w-full rounded-lg border border-default-strong bg-neutral-primary px-3 py-2 text-sm text-heading placeholder:text-muted shadow-sm transition focus:border-brand focus:ring-2 focus:ring-brand/25 focus:outline-none"
          />
        </label>

        <!-- Timestamps are generated by the server; shown read-only -->
        <dl v-if="note" class="grid grid-cols-2 gap-3 rounded-lg bg-neutral-secondary-soft px-3 py-2 text-xs">
          <div>
            <dt class="text-muted">Created At</dt>
            <dd class="font-medium text-heading">{{ formatDateTime(note.createdAt) }}</dd>
          </div>
          <div>
            <dt class="text-muted">Updated At</dt>
            <dd class="font-medium text-heading">
              {{ isEdited(note.createdAt, note.updatedAt) ? formatDateTime(note.updatedAt) : 'Not edited yet' }}
            </dd>
          </div>
        </dl>
        <p v-else class="text-xs text-muted">Created At and Updated At are set automatically.</p>

        <p v-if="errorMessage" class="rounded-lg bg-danger-soft px-3 py-2 text-sm text-fg-danger">{{ errorMessage }}</p>

        <div class="flex justify-end gap-2">
          <BaseButton type="button" variant="secondary" @click="emit('close')">Cancel</BaseButton>
          <BaseButton type="submit" :loading="isSaving">{{ isEditMode ? 'Save changes' : 'Create note' }}</BaseButton>
        </div>
      </form>
    </div>
  </div>
</template>
